### ISSUE TITLE
Separate docker panel

### ISSUE THREAD

**Issue by GWan1234** [bacco007/HomeAssistantConfig#16]
I found your dock card. It's beautiful. I want to post it separately.
Lovelace, it will adapt to HACS. Can I use it and modify some code? Of course, I will explain that the original work of all this comes from your dedication.

**Comment by bacco007** [comment]
Go for it!  I haven't had much of a chance of doing anything with it recently, so I'm happy for it to be developed further!

**Comment by GWan1234** [comment]
Thank you for your permission!
