### ISSUE TITLE
docker-card not working offline

### ISSUE THREAD

**Issue by molly200** [bacco007/HomeAssistantConfig#17]
**Describe the bug**
"docker-card" not working offline. Card works well if the HA is connected to internet. It disappears with a “Custom element doesn’t exist: docker-card” error, when internet is not available or HA is offline.
**To Reproduce**

**Expected behavior**
 It seems that the card is dependent on the /unpkg.com/lit-element@2.0.1/lit-element.js.
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I was wondering is this card can be made to work offline, with the existing HA lit-element, or the card-tools lit-element from thomasloven? 
Thanks

**Comment by GWan1234** [comment]
@molly200 
Maybe you can try this project?
https://github.com/Tao173/docker-card
This is a card, completely (almost 100%) dependent on the work of bacco007, I modified it to only support Chinese.
I'm truly grateful for his work.
