### ISSUE TITLE
hass_main_config question?

### ISSUE THREAD

**Issue by johntdyer** [bacco007/HomeAssistantConfig#83]
Hey there, love this config , very inspiring !!!  I am trying to understand ha_overview python script and it seems to reference an entity called sensor.hass_main_config which I cant find in your config.. could you shed some light on that one?

**Comment by bacco007** [comment]
Hmm, good question - I'm not sure what that was referring to (I must have had it previously and cleaned up)

I'll have a look into it and see what I can find

EDIT: Found it - https://github.com/bacco007/HomeAssistantConfig/blob/07abff16673f14fe11c0b1137db5878393b60e7b/integrations/packages/ha_version.yaml#L2-L17

**Comment by johntdyer** [comment]
thank you !

**Comment by Hankanman** [comment]
Can you advise the url format/target/docs, not sure which api you are hitting
