### ISSUE TITLE
ha_uptime_hours location

### ISSUE THREAD

**Issue by johntdyer** [bacco007/HomeAssistantConfig#86]
Hello,

 Me again... you're config is really inspiring, loving working through it to understand all its intricacies ....  Was looking at some of the alert logic and noticed `ha_uptime_hours` but I am not able to see where that sensor is defined or derived...  Could you maybe point me in the right direction ?  Thanks !

-John

**Comment by bacco007** [comment]
Hi John - thanks!

That sensor uses the Uptime integration, which is configurable via the UI: https://www.home-assistant.io/integrations/uptime
